name: Electron Builder Action
author: Samuel Meuli
description: GitHub Action for building and releasing Electron apps

inputs:
  github_token:
    description: GitHub authentication token
    required: true
  mac_certs:
    description: Base64-encoded code signing certificate for macOS
    required: false
  mac_certs_password:
    description: Password for decrypting `mac_certs`
    required: false
  branch:
    description: Branch on Github
    required: false
    default: master
  windows_certs:
    description: Base64-encoded code signing certificate for Windows
    required: false
  windows_certs_password:
    description: Password for decrypting `windows_certs`
    required: false

runs:
  using: node12
  main: index.js

branding:
  icon: upload-cloud
  color: blue
